spring:
  datasource:
    url: jdbc:h2:file:~/db/h2;IGNORECASE=TRUE;MODE=MySQL
    username: fd
    password: midnight1000
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none