spring:
  datasource:
    azure:
      passwordless-enabled: true
    url: jdbc:mysql://tortolla-mysql.mysql.database.azure.com:3306/tortolla?serverTimezone=UTC
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none