spring:
  datasource:
    url: jdbc:h2:~/db/h2;IGNORECASE=TRUE;MODE=MySQL;FILE_LOCK=SOCKET
    username: fd
    password: midnight1000
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none