spring:
  datasource:
    url: jdbc:mysql://tortolla-mysql.mysql.database.azure.com:3306/tortolla?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none